/* Generated by tools/generate_protocol_constants.py. Do not edit. */
#ifndef TUMOVGM_PROTOCOL_IDS_H
#define TUMOVGM_PROTOCOL_IDS_H

#include <stdint.h>

#define TUMOVGM_PROTOCOL_MAJOR UINT8_C(1)
#define TUMOVGM_PROTOCOL_MINOR UINT8_C(1)
#define TUMOVGM_PROTOCOL_MAX_PAYLOAD UINT16_C(512)
#define TUMOVGM_PROTOCOL_MAGIC_0 UINT8_C(0x54)
#define TUMOVGM_PROTOCOL_MAGIC_1 UINT8_C(0x56)
#define TUMOVGM_PROTOCOL_MAGIC_2 UINT8_C(0x47)
#define TUMOVGM_PROTOCOL_MAGIC_3 UINT8_C(0x31)

typedef enum TumovgmFrameKind {
    TumovgmFrameKindRequest = 1,
    TumovgmFrameKindResponse = 2,
    TumovgmFrameKindEvent = 3,
    TumovgmFrameKindError = 4,
} TumovgmFrameKind;

typedef enum TumovgmFrameFlag {
    TumovgmFrameFlagMore = 1,
    TumovgmFrameFlagAckRequired = 2,
} TumovgmFrameFlag;

typedef enum TumovgmMessage {
    TumovgmMessageHello = 1,
    TumovgmMessageCapabilities = 2,
    TumovgmMessageSessionOpen = 3,
    TumovgmMessageSessionClose = 4,
    TumovgmMessageCancel = 5,
    TumovgmMessagePing = 6,
    TumovgmMessageDeviceInfo = 7,
    TumovgmMessageStreamCredit = 16,
    TumovgmMessageStreamData = 17,
    TumovgmMessageStreamEnd = 18,
} TumovgmMessage;

typedef enum TumovgmError {
    TumovgmErrorUnsupportedVersion = 1,
    TumovgmErrorUnsupportedMessage = 2,
    TumovgmErrorMalformed = 3,
    TumovgmErrorBadState = 4,
    TumovgmErrorBusy = 5,
    TumovgmErrorTimeout = 6,
    TumovgmErrorCancelled = 7,
    TumovgmErrorNoCapability = 8,
    TumovgmErrorOverflow = 9,
    TumovgmErrorInternal = 10,
} TumovgmError;

typedef enum TumovgmCapabilityBit {
    TumovgmCapabilityBitVideoOut = 0,
    TumovgmCapabilityBitImu = 1,
    TumovgmCapabilityBitGpioCapture = 2,
    TumovgmCapabilityBitHwTrigger = 3,
    TumovgmCapabilityBitTraceBuffer = 4,
    TumovgmCapabilityBitDecoderUart = 5,
    TumovgmCapabilityBitDecoderSpi = 6,
    TumovgmCapabilityBitDecoderI2C = 7,
    TumovgmCapabilityBitUsbDevice = 8,
    TumovgmCapabilityBitUsbHost = 9,
} TumovgmCapabilityBit;

typedef enum TumovgmRole {
    TumovgmRoleFlipper = 1,
    TumovgmRoleVgm = 2,
    TumovgmRoleHostDiagnostic = 3,
} TumovgmRole;

typedef enum TumovgmHardwareTarget {
    TumovgmHardwareTargetVgmRp2040 = 1,
} TumovgmHardwareTarget;

#endif
