#pragma once

// Icon assets are auto-generated by the build system
// from the images/ folder. If no custom icons are needed,
// this file can remain minimal.

// If you place .png files in an images/ folder,
// the build system generates icon references automatically.
// Access them via &I_iconname
