#if defined(ARF_PROFILE_KEELOQ)
ADD_SCENE(subghz, start, Start)
ADD_SCENE(subghz, show_error, ShowError)
ADD_SCENE(subghz, show_error_sub, ShowErrorSub)
ADD_SCENE(subghz, keeloq_keys, KeeloqKeys)
ADD_SCENE(subghz, keeloq_key_edit, KeeloqKeyEdit)
ADD_SCENE(subghz, keeloq_bf2, KeeloqBf2)
ADD_SCENE(subghz, keeloq_decrypt, KeeloqDecrypt)
#elif defined(ARF_PROFILE_COUNTER)
ADD_SCENE(subghz, start, Start)
ADD_SCENE(subghz, show_error, ShowError)
ADD_SCENE(subghz, show_error_sub, ShowErrorSub)
ADD_SCENE(subghz, counter_bf, CounterBf)
#elif defined(ARF_PROFILE_CAR)
ADD_SCENE(subghz, start, Start)
ADD_SCENE(subghz, show_error, ShowError)
ADD_SCENE(subghz, show_error_sub, ShowErrorSub)
ADD_SCENE(subghz, car_emulate, CarEmulate)
#elif defined(ARF_PROFILE_FA)
ADD_SCENE(subghz, start, Start)
ADD_SCENE(subghz, show_error, ShowError)
ADD_SCENE(subghz, frequency_analyzer, FrequencyAnalyzer)
#elif defined(ARF_PROFILE_PSA)
ADD_SCENE(subghz, start, Start)
ADD_SCENE(subghz, show_error, ShowError)
ADD_SCENE(subghz, show_error_sub, ShowErrorSub)
ADD_SCENE(subghz, psa_decrypt, PsaDecrypt)
#else
ADD_SCENE(subghz, start, Start)
ADD_SCENE(subghz, receiver, Receiver)
ADD_SCENE(subghz, receiver_config, ReceiverConfig)
ADD_SCENE(subghz, protocol_pack_info, ProtocolPackInfo)
ADD_SCENE(subghz, receiver_info, ReceiverInfo)
ADD_SCENE(subghz, save_name, SaveName)
ADD_SCENE(subghz, save_success, SaveSuccess)
ADD_SCENE(subghz, saved, Saved)
ADD_SCENE(subghz, transmitter, Transmitter)
#if !defined(ARF_PROFILE_STANDARD)
ADD_SCENE(subghz, car_emulate, CarEmulate)
ADD_SCENE(subghz, car_emulate_settings, CarEmulateSettings)
ADD_SCENE(subghz, counter_bf, CounterBf)
ADD_SCENE(subghz, psa_decrypt, PsaDecrypt)
#endif
ADD_SCENE(subghz, show_error, ShowError)
ADD_SCENE(subghz, show_error_sub, ShowErrorSub)
ADD_SCENE(subghz, saved_menu, SavedMenu)
ADD_SCENE(subghz, delete, Delete)
ADD_SCENE(subghz, delete_success, DeleteSuccess)
ADD_SCENE(subghz, set_type, SetType)
ADD_SCENE(subghz, set_key, SetKey)
ADD_SCENE(subghz, set_serial, SetSerial)
ADD_SCENE(subghz, set_button, SetButton)
ADD_SCENE(subghz, set_counter, SetCounter)
ADD_SCENE(subghz, set_seed, SetSeed)
ADD_SCENE(subghz, frequency_analyzer, FrequencyAnalyzer)
ADD_SCENE(subghz, radio_settings, ExtModuleSettings)
ADD_SCENE(subghz, read_raw, ReadRAW)
ADD_SCENE(subghz, more_raw, MoreRAW)
ADD_SCENE(subghz, decode_raw, DecodeRAW)
ADD_SCENE(subghz, delete_raw, DeleteRAW)
ADD_SCENE(subghz, need_saving, NeedSaving)
ADD_SCENE(subghz, protocol_list, ProtocolList)
ADD_SCENE(subghz, rpc, Rpc)
ADD_SCENE(subghz, signal_settings, SignalSettings)
#endif
